let interval='5m';
let serverEpoch=0, syncedAt=0;
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const riverLike=new Set(['river','crypto-river']);

async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error((await r.json()).error||r.statusText);return r.json()}
async function syncServerTime(){try{const d=await getJson('/api/time');serverEpoch=new Date(d.utc).getTime();syncedAt=Date.now()}catch(e){}}
async function loadLivePrice(){try{const d=await getJson('/api/price');$('live-price').textContent=money(d.price);$('live-price-time').textContent=`${new Date(d.updated_at).toISOString().slice(11,19)} UTC`;$('live-price').className='live'}catch(e){$('live-price-time').textContent='Цена недоступна';$('live-price').className='negative'}}
function tickServerTime(){if(!serverEpoch)return;const now=new Date(serverEpoch+Date.now()-syncedAt);$('server-time').textContent=now.toISOString().slice(0,19).replace('T',' ')+' UTC'}
async function loadHistory(){
  $('history').disabled=false;
  if(interval==='river'){
    const d=await getJson('/api/river/history');
    $('history').innerHTML='<option value="">Текущий River</option>'+d.rows.map(r=>`<option value="${escapeHtml(r.id)}">${escapeHtml(new Date(r.forecast_time).toISOString().slice(0,16).replace('T',' '))} · ${escapeHtml(r.model)}</option>`).join('');
    return;
  }
  if(interval==='crypto-river'){
    const d=await getJson('/api/crypto-river/history');
    $('history').innerHTML='<option value="">Текущий Crypto River</option>'+d.rows.map(r=>`<option value="${escapeHtml(r.id)}">${escapeHtml(new Date(r.forecast_time).toISOString().slice(0,16).replace('T',' '))} · ${escapeHtml(r.model)}</option>`).join('');
    return;
  }
  const d=await getJson(`/api/history?interval=${interval}`);$('history').innerHTML='<option value="">Текущий прогноз</option>'+d.files.map(f=>`<option value="${escapeHtml(f)}">${escapeHtml(f.replace('.json',''))}</option>`).join('')}
async function load(){try{$('status').textContent='Обновление…';const file=$('history').value;let url;if(interval==='river')url=file?`/api/river/history/file?id=${encodeURIComponent(file)}`:'/api/river/current';else if(interval==='crypto-river')url=file?`/api/crypto-river/history/file?id=${encodeURIComponent(file)}`:'/api/crypto-river/current';else url=file?`/api/history/file?interval=${interval}&name=${encodeURIComponent(file)}`:`/api/current?interval=${interval}`;render(await getJson(url));$('status').textContent='Данные актуальны'}catch(e){$('status').textContent=`Ошибка: ${e.message}`}}
function render(d){const f=d.forecast,last=f[f.length-1],change=(last.point/d.last_close-1)*100,isRiver=riverLike.has(interval),isCryptoRiver=interval==='crypto-river',isXreg=!isRiver&&f.some(r=>r.xreg_point!=null),componentLabel=isXreg?'TimesFM + XReg':'Факторы (старый)';$('last').textContent=money(d.last_close);$('forecast').textContent=money(last.point);$('change').textContent=`${change>=0?'+':''}${change.toFixed(3)}%`;$('change').className=change>=0?'positive':'negative';$('range').textContent=isRiver?'Нет вероятностного диапазона':`${money(last.q10)} — ${money(last.q90)}`;$('generated').textContent=isRiver?`Создан: ${new Date(d.generated_at).toLocaleString('ru-RU')} · ${d.model} · ${isCryptoRiver?'ONLINE 24H':'SHADOW'}`:`Создан: ${new Date(d.generated_at).toLocaleString('ru-RU')} · ${f.length} точек · ${isXreg?'TimesFM + XReg':'старый ансамбль'}`;$('table-head').innerHTML=isRiver?'<tr><th>Время UTC</th><th>River прогноз</th><th>Последняя цена</th><th>Движение</th><th>Режим</th></tr>':`<tr><th>Время UTC</th><th>Итог</th><th>TimesFM</th><th>${componentLabel}</th><th>q10–q90</th></tr>`;$('rows').innerHTML=isRiver?f.map(r=>{const move=r.predicted_return_pct??((r.point/d.last_close-1)*100);const direction=r.direction??(move>=0?'UP':'DOWN');return `<tr><td>${new Date(r.timestamp).toISOString().slice(0,16).replace('T',' ')}</td><td>${money(r.point)}</td><td>${money(d.last_close)}</td><td>${move>=0?'+':''}${move.toFixed(3)}% · ${escapeHtml(direction)}</td><td>${isCryptoRiver?'online 24h':'shadow'}</td></tr>`}).join(''):f.map(r=>`<tr><td>${new Date(r.timestamp).toISOString().slice(0,16).replace('T',' ')}</td><td>${money(r.point)}</td><td>${money(r.timesfm_point)}</td><td>${money(isXreg?r.xreg_point:r.factors_point)}</td><td>${money(r.q10)} — ${money(r.q90)}</td></tr>`).join('');draw(d)}
function draw(d){const data=d.forecast,w=1100,h=360,p={l:68,r:18,t:18,b:34};const single=data.length===1,chartData=single?[{...data[0],timestamp:d.generated_at,point:d.last_close},data[0]]:data;const values=chartData.flatMap(x=>[x.q10??x.point,x.q90??x.point]).concat(d.last_close),min=Math.min(...values),max=Math.max(...values),span=max-min||1;x=i=>p.l+i*(w-p.l-p.r)/Math.max(1,chartData.length-1);y=v=>p.t+(max-v)*(h-p.t-p.b)/span;const upper=chartData.map((v,i)=>`${x(i)},${y(v.q90??v.point)}`).join(' '),lower=[...chartData].reverse().map((v,j)=>`${x(chartData.length-1-j)},${y(v.q10??v.point)}`).join(' '),line=chartData.map((v,i)=>`${x(i)},${y(v.point)}`).join(' '),dots=chartData.map((v,i)=>`<circle class="${single&&i===0?'current-dot':'forecast-dot'}" cx="${x(i)}" cy="${y(v.point)}" r="${single?7:3}"/>`).join('');let grid='';for(let i=0;i<5;i++){const val=min+span*i/4,yy=y(val);grid+=`<line class="grid" x1="${p.l}" y1="${yy}" x2="${w-p.r}" y2="${yy}"/><text class="axis" x="${p.l-8}" y="${yy+4}" text-anchor="end">${Math.round(val).toLocaleString()}</text>`}const labelStep=Math.max(1,Math.floor(chartData.length/6));let labels='';for(let i=0;i<chartData.length;i+=labelStep)labels+=`<text class="axis" x="${x(i)}" y="${h-8}" text-anchor="middle">${new Date(chartData[i].timestamp).toISOString().slice(11,16)}</text>`;$('chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${grid}<polygon class="area" points="${upper} ${lower}"/><line class="last-line" x1="${p.l}" y1="${y(d.last_close)}" x2="${w-p.r}" y2="${y(d.last_close)}"/><polyline class="price-line" points="${line}"/>${dots}${labels}</svg>`}
document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelector('.tab.active').classList.remove('active');b.classList.add('active');interval=b.dataset.interval;await loadHistory();load()});$('history').onchange=load;$('refresh').onclick=async()=>{await loadHistory();load()};
loadHistory().then(load);setInterval(()=>{if(!$('history').value)load()},60000);
syncServerTime().then(tickServerTime);setInterval(tickServerTime,1000);setInterval(syncServerTime,60000);
loadLivePrice();setInterval(loadLivePrice,5000);
