[Service]
PrivateDevices=true
ProtectKernelLogs=true
ProtectClock=true
ProtectHostname=true
ProtectSystem=strict
ProtectHome=read-only
ProtectProc=invisible
ProcSubset=pid
CapabilityBoundingSet=
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictSUIDSGID=true
RestrictRealtime=true
MemoryDenyWriteExecute=true
SystemCallArchitectures=native
UMask=0077
